---
# a unix path-friendly name (IE, no spaces or special characters)
project_name: devopsDummy

# the base path to install to. You should not need to change this.
install_root: /srv

# any directories that need to be added to the PYTHONPATH.
pythonpath: "{{ install_root }}/{{ project_name }}"

# the git repository URL for the project
project_repo: git@github.com:alexforever86/devopsDummy.git

# a private key that has access to the repository URL
ssh_private_key: ~/.ssh/id_rsa

# apt packages, you should not need to change this unless you have packages
# listed in your requirements.txt that depend on system packages.
system_packages:
  - git
  - python-pip
  - python-dev
